- hosts: all
  become: yes
  become_user: roshan
  tasks:
   - name: Copy container deployment file to Worker Node
     copy:
       src: ./containers/
       dest: /home/roshan        
   - name: change user permission of Yaml files
     file: path=/home/roshan/ owner=roshan group=wheel mode=0775 state=directory recurse=yes

- hosts: k8s-worker-sh1
  become: yes
  become_user: roshan
  tasks:

    - name: Build docker image for medhavi-app on kubernetes-worker node
      shell: docker build -f Dockerfile -t medhavi-app:v1 .

- hosts: k8s-master-sh1
  become: yes
  become_user: roshan
  tasks:
  
    - name: Create containers for medhavi-app
      shell: kubectl apply -f app.yaml
