- hosts: kubernetes-worker
  tasks:

   - name: Copy container deployment file to Worker Node
     copy:
       src: ./containers/
       dest: /home/centos
   - name: Add Non-root user:centos to wheel group
     shell: usermod -aG wheel centos     
   - name: change user permission of Yaml files
     shell: sudo chown -R centos:centos /home/centos/
- hosts: kubernetes-worker
  become: yes
  become_user: centos
  tasks:
  
    - name: Create persistent volume for mysql-db
      shell: kubectl apply -f app.yaml
