---
- hosts: all
  gather_facts: no
  become: yes
  tasks:

   - name: Disabling Swap on all nodes
     shell: swapoff -a

   - name: Commenting Swap entries in /etc/fstab
     replace:
      path: /etc/fstab
      regexp: '(.*swap*)'
      replace: '#\1'

   - name: remove firewalld
     package:
       name: firewalld
       state: absent

   - name: install Yum-utils
     dnf:
       name: yum-utils
       state: present

   - name: Install device-mapper-persistent-data
     dnf:
       name: device-mapper-persistent-data
       state: present

   - name: Install lvm2
     dnf:
       name: lvm2
       state: present

   - name: Add Docker repo
     get_url:
       url: https://download.docker.com/linux/centos/docker-ce.repo
       dest: /etc/yum.repos.d/docer-ce.repo
     become: yes

   - name: Enable Docker Edge repo
     ini_file:
       dest: /etc/yum.repos.d/docer-ce.repo
       section: 'docker-ce-edge'
       option: enabled
       value: 0
     become: yes

   - name: Enable Docker Test repo
     ini_file:
       dest: /etc/yum.repos.d/docer-ce.repo
       section: 'docker-ce-test'
       option: enabled
       value: 0
     become: yes

   - name: Install Docker
     package:
       name: docker-ce
       state: present
     become: yes

   - name: Start Docker service
     service:
       name: docker
       state: started
       enabled: yes
     become: yes

   - name: Adding non-admin user to group docker
     user:
       name: roshan
       groups: docker
       append: yes
     become: yes

   - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
     sysctl:
      name: net.bridge.bridge-nf-call-ip6tables
      value: 1
      state: present

   - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
     sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      state: present

   - name: add Kubernetes' YUM repository
     yum_repository:
      name: Kubernetes
      description: Kubernetes YUM repository
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      gpgcheck: yes

   - name: install kubelet
     dnf:
        name: kubelet
        state: present
        update_cache: true

   - name: install kubeadm
     dnf:
        name: kubeadm
        state: present

   - name: start kubelet
     service:
       name: kubelet
       enabled: yes
       state: started
