---
- hosts: masters
  gather_facts: no
  become: yes
  tasks:
   - name: install kubectl
     dnf:
        name: kubectl
        state: present
        allow_downgrade: yes

   - name: Pulling images required for setting up a Kubernetes cluster
     shell: kubeadm config images pull

   - name: initialize the cluster
     shell: sudo kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=all >> cluster_initialized.txt
     register: output
     args:
       chdir: $HOME
       creates: cluster_initialized.txt

   - name: create .kube directory
     become: yes
     become_user: roshan
     file:
       path: $HOME/.kube
       state: directory
       mode: 0755

   - name: copy admin.conf to user's kube config
     copy:
       src: /etc/kubernetes/admin.conf
       dest: /home/roshan/.kube/config
       remote_src: yes
       owner: root

   - name: install Pod network
     become: yes
     become_user: roshan
     shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
     args:
       chdir: $HOME
       creates: pod_network_setup.txt
